<h3 class="centered">Universidad Modular Abierta(UMA)</h3>
<div class="divider"></div>
<div class="row"> 
  </row>
  <tbody>
    <?= form::open('universidades/guardar', 'post', 'class="col s12"'); ?>
    <div class="row">
      <div class="input-field col s12">
        <table>
           <div class="input-field col s12">
              <th>Direccion</th>
              <th>Telefono</th>
           <div>
       </table>
       <table>
           <div class="input-field col s12">
              <th>Facultad</th>
              <th>Carreras</th>
           <div>
       </table>
       <table>
           <div class="input-field col s12">
              <th>Matricula</th>
              <th>Mensualidad</th>
           <div>
       </table>
       <table>
           <div class="input-field col s12">
              <th>Carreras</th>
              <th>Ciclo I</th>
              <th>Ciclo II</th>
              <th>Ciclo III</th>
              <th>Ciclo IV</th>
              <th>Ciclo V</th>
              <th>Ciclo VI</th>
              <th>Ciclo VII</th>
              <th>Ciclo VIII</th>
              <th>Ciclo IX</th>
              <th>Ciclo X</th>
            <div>
       </table>
      </div>   
     </div>
 </tbody>

</div>