<div class="content">
    <?php view::content() ?>
    <h3></h3>
       <tbody>
       <?=form::open('departamentos/guardar','post','class="col s12"');?>
    <div class="row">
         <div class="input-field col s12">
               <?=form::text('nombre de universidad.nombre de universidad',)?>
               <?= form::label('Nombre de Universidad','nombre de universidad')?>
            </div>
            <table>
                 <thead>
                    <th>Ciclo I</th>
                    <th>Ciclo II</th>
                    <th>Ciclo III</th>
                    <th>ciclo IV</th>
                 </thead>
            
            </div>
            <div class="input-field col s12">
              <table>
                 <thead>
                    <th>Ciclo I</th>
                    <th>Ciclo II</th>
                    <th>Ciclo III</th>
                    <th>ciclo IV</th>
                 </thead>
            
                </table>
            </div>
          
            
              

            
        
         </tbody>
    
</div>
