<?php view::content() ?>
<div class="container">
    <div class="separador"></div>
    <div class="cuadro">
        <?= form::open() ?>
            <div class="row">
                <div class="input-field col s12">
                    <input type="text" name="email" placeholder ="Ej: correo@corporation.com">
                    <label for="email"></label>
                </div>
                <div class="input-field col s12">
                    <input type="password" name="contrasenia" placeholder="Ej: ContraseniaSegura183">
                    <label for="contrasenia"></label>
                </div>
                <div class="row">
                    <div class="input-field col s5 ">
                        <?=form::submit('INICIAR SESION','class="btn blue darken-8"')?>
                    </div>        
                </div>
            </div>
        <?= form::close() ?>
    </div>
</div>