<?php view::content() ?>
<div class="contenedor">
    <div class="item">
        <?= form::open('universidades/login', 'method="post"') ?>
        <div class="row">
            <div class="input-field col s12">
                <input type="text" name="email" placeholder="Gmail">
            </div>
            <div class="input-field col s12">
                <span class="icon-eye" id="eye">
                    <i class="fa-solid fa-eye-slash"></i>
                </span>
                <input type="password" name="password" placeholder="contraseña">
            </div>
            <div class="row" id="btn">
                <div class="input-field col s5" id="button">
                 <button type="submit" class="btn blue darken-8" name="boton">INICIAR SESION</button>
                 </div>
            </div>
        </div>
        <?= form::close() ?>
    </div>
</div>