<h1>registro  personas</h1>
<div class="divider"></div>
<div class="row">
 <?=form::open('personas/guardar','post','class="col s12"');?>
    <div class="row">
         <div class="input-field col s6">
               <?=form::text('personas.nombres')?>
               <?= form::label('Nombres','nombres')?>
            </div>
            <div class="input-field col s6">
               <?= form::text('personas.apellidos','required')?>
               <?= form::label('Apellidos','apellidos')?>
           </div>

            </div>
        </div>
        <div class="row">
        <div class="input-field col s6">
               <?= form::number('personas.edad','required')?>
               <?= form::label('Edad','edad')?>
          </div>
          <div class="row">
             <div class="input-field col s6">
               <?= form::text('personas.email','required')?>
               <?= form::label('Email','email')?>
          </div>
          <div class="row">
             <div class="input-field col s6">
               <?= form::text('personas.dui','required')?>
               <?= form::label('Dui','dui')?>
          </div>
          <div class="row">
             <div class="input-field col s6">
               <?= form::text('personas.telefono','required')?>
               <?= form::label('Telefono','telefono')?>


          </div>
          <div class="row">
             <div class="input-field col s6">
               <?= form::date('personas.fecha')?>
               <?= form::label('Nacimiento','fecha')?>

          
          </div>
         

          <div class="row"></div>
          <?=form::submit('Guardar','class="btn green darken-4"')?>
          <?=form::reset('Limpiar','class="btn yellow darken-4"')?>
        </div>
    <?= form::close();?>
</div>