<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css">
    <title>Document</title>
    <style>
        body {
            width: 100%;
            height: 100vh;
            background: rgb(2, 0, 36);
            background: linear-gradient(328deg, rgba(2, 0, 36, 1) 0%, rgba(188, 187, 195, 1) 0%, rgba(173, 241, 255, 1) 76%, rgba(0, 212, 255, 1) 100%);
        }

        .contenedor {
            height: 100vh;
            display: flex;
            align-items: center;
            justify-content: center;
            position: relative;
        }

        .item {
            width: 450px;
            padding: 25px;
            padding-top: 35px;
            height: 350px;
            border: 4px solid #000000;
            background: #ffff;
            border-radius: 30px;
            position: relative;
        }
        #eye {
            position: absolute;
            right: 10px;
            top: 50%;
            transform: translateY(-50%);
            font-size: 30px;
            cursor: pointer;
            transition: .4s ease all;
        }
        .eyes:hover {
            color: steelblue;   
        }
        h1 {
            color: red;
        }
    </style>
</head>

<body>

    <div class="container">
        <?php view::content() ?>
    </div>
    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script>
            const iconEye = document.querySelector(".icon-eye");

            

            iconEye.addEventListener("click", function () {
                // console.log(this.nextElementSibling.type);
                const icon = this.querySelector("i");
                // console.log(this.nextElementSibling);
                if (this.nextElementSibling.type === "password") {
                    this.nextElementSibling.type = "text";
                    icon.classList.remove("fa-eye-slash");
                    icon.classList.add("fa-eye");
                
                } else {
                    this.nextElementSibling.type = "password";
                    icon.classList.remove("fa-eye");
                    icon.classList.add("fa-eye-slash");

                    //<i class="fa-solid fa-eye-slash"></i>
                    //<i class="fa-solid fa-eye"></i>
                }
            });

    </script>
</body>

</html>