<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Compiled and minified CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <title>Document</title>
    <style>
        body{
            background-color:#000000;
            
            
        }
        .separador {
            padding-top: 150px;
        }
        .cuadro {
            background-color:#ffffff;
            border: solid 1px #000000;
            border-radius: 30px;
        }
    </style>
</head>
<body>

    <div class="container">
      <?php view::content() ?>
    </div>
<!-- Compiled and minified JavaScript -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

</body>
</html>